In [8]:
import numpy as np

print(np.__version__)

1.24.4


In [11]:
arr=np.array([1,2,5,6,8])
print(arr)
print(type(arr))

arr1=np.array((1,5,8,9,7,8))
print(arr1)
print(type(arr1))

[1 2 5 6 8]
<class 'numpy.ndarray'>
[1 5 8 9 7 8]
<class 'numpy.ndarray'>


In [22]:
# 0 dimentional array

arr=np.array((45))
print(arr.ndim)

# 1-D array

arr1d=np.array([4,5,8,9,7])
print(arr1d.ndim)

# 2-D array

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)

# 3-D array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(arr.ndim)

0
1
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [23]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [28]:
arr = np.array([1, 5, 3, 8])
print(arr[1])
print(arr[1] + arr[3])

5
13


In [33]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[1, 4])

2nd element on 1st row:  10


In [36]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [42]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

# 2-D
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)
    
for x in arr:
  for y in x:
    print(y)


1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [47]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.stack((arr1, arr2), axis=1)

print("arr",arr)

arr = np.hstack((arr1, arr2))

print("array",arr)

arr [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
array [[1 2 5 6]
 [3 4 7 8]]
