In [12]:
# Ufuncs example without using ufunc
x=[1,2,3,4,5]
y=[5,8,9,6,4]
z=[]
# print(x,y,z)
for i, j in zip(x,y):
 z.append(i+j)
print(z)

[1, 2, 3, 4, 5] [5, 8, 9, 6, 4] []
[6, 10, 12, 10, 9]


In [15]:
# Example using Ufunc
import numpy as np
x=[4,2,3,1]
y=[4,5,6,7]
z=np.add(x,y)
print(z)


[8 7 9 8]


In [20]:
# using own function
def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [35]:
# Simple Arithmetic

import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,8,9])
arr3=np.add(arr1,arr2)
print("addition ",arr3)

arr3=np.subtract(arr2,arr1)
print("subtract ", arr3)

arr3=np.multiply(arr1,arr2)
print("Multiply ",arr3)

arr3=np.divide(arr1, arr2)
print("divide ",arr3)

arr3=np.power(arr1, arr2)
print("power ",arr3)

arr3=np.mod(arr1, arr2)
print("Mod ",arr3)

arr3= np.remainder(arr1, arr2)
print("remainder ", arr3)

newarr = np.divmod(arr1, arr2)
print("divmod ",newarr)

newarr = np.absolute(arr2)
print("absolute ",newarr)

addition  [ 5  7  9 12 14]
subtract  [3 3 3 4 4]
Multiply  [ 4 10 18 32 45]
divide  [0.25       0.4        0.5        0.5        0.55555556]
power  [      1      32     729   65536 1953125]
Mod  [1 2 3 4 5]
remainder  [1 2 3 4 5]
divmod  (array([0, 0, 0, 0, 0]), array([1, 2, 3, 4, 5]))
[4 5 6 8 9]


In [42]:
# Rounding Decimals
arr = np.trunc([-3.1666, 3.6667])
print(arr)

arr = np.fix([-3.1666, 3.6667])
print(arr)

arr = np.around(3.1666, 2)
print(arr)

arr = np.floor([-3.1666, 3.6667])
print(arr)

arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  3.]
[-3.  3.]
3.17
[-4.  3.]
[-3.  4.]


In [51]:
# NumPy Logs
arr = np.arange(1, 10)
print("log2 ",np.log2(arr))
print("log10 ",np.log10(arr))
print("log ",np.log(arr))

from math import log
import numpy as np
nplog = np.frompyfunc(log, 2, 1)
print("nplog ",nplog(100, 15))

log2  [0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
log10  [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
log  [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
nplog  1.7005483074552052


In [58]:
# NumPy Summations
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 5, 9])

newarr = np.add(arr1, arr2)
print("add",newarr)
# sum of all array no total
newarr = np.sum([arr1, arr2])
print("sum",newarr) 

# sum of array indivisial
newarr = np.sum([arr1, arr2], axis=1)
print(newarr)

# Cummulative Sum
print("Cummulative Sum")
newarr = np.cumsum(arr1)
print(newarr)
newarr = np.cumsum(arr2)
print(newarr)


add [ 2  7 12]
sum 21
[ 6 15]
Cummulative Sum
[1 3 6]
[ 1  6 15]


In [65]:
# NumPy Products
x = np.prod(arr1)
print(x)
x = np.prod(arr2)
print(x)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
x = np.prod([arr1, arr2])
print(x)
newarr = np.prod([arr1, arr2], axis=1)
print(newarr)
newarr = np.cumprod(arr2)
print(newarr)

24
1680
40320
[  24 1680]
[   5   30  210 1680]


In [67]:
# NumPy Differences

arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

newarr = np.diff(arr, n=2)
print(newarr)

[  5  10 -20]
[  5 -30]


In [77]:
# NumPy LCM Lowest Common Multiple
num1 = 8
num2 = 6

x = np.lcm(num1, num2)
print("lcm ",x)
x = np.gcd(num1, num2)
print("gcd ",x)

arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print("lcm",x)

x = np.gcd.reduce(arr)
print("gcd",x)

arr = np.arange(1, 11)
x = np.lcm.reduce(arr)
print(x)

lcm  24
gcd  2
lcm 18
gcd 3
2520


In [88]:
# NumPy Trigonometric Functions
x = np.sin(np.pi/2)
print(x)
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)


arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

x = np.arcsin(1.0)
print(x)

arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print(x)

base = 3
perp = 4
x = np.hypot(base, perp)
print(x)

1.0
[1.         0.8660254  0.70710678 0.58778525]
[1.57079633 3.14159265 4.71238898 6.28318531]
[ 90. 180. 270. 360.]
1.5707963267948966
[ 1.57079633 -1.57079633  0.10016742]
5.0


In [95]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)
newarr = np.setdiff1d(arr, arr, assume_unique=True)
print(newarr)

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setxor1d(set1, set2, assume_unique=True)
print(newarr)


[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[3 4]
[]
[1 2 5 6]
